### ISSUE TITLE
Обновление словарей

### ISSUE THREAD

**Issue by malygin** [kmike/pymorphy2-dicts#3]
Планируется ли обновление словарей?  В opencorpa накопилось много актуальных изменений, если нет, то где найти инструкции по самостоятельной сборке словарей?

**Comment by kmike** [comment]
Если склонировать этот репозиторий, установить все зависимости и выполнить `update.py ru all`, то рядом должна создаться папка с питоньим пакетом pymorphy2_dicts_ru, который можно поставить, чтоб получить обновленные словари. 

На pypi словари обновлю сегодня.

Еще внимательно - словари обновляются для pymorphy2 master; для pymorphy2 с pypi - нет.

**Comment by malygin** [comment]
@kmike ага, спасибо

**Comment by Yiivgeny** [comment]
@kmike, мне как-то раз удалось обновить словари для pymorphy из pypi, я так понимаю речь про версию 0.8. Я выбирал какой-то из коммитов этого репозитория близкий по дате к релизу 0.8, и они собрались корректно.

Хотелось бы чтобы был авторский тег на нужный коммит в этом репозитории, чтобы быть спокойным на этот счет и иметь возможность собирать словари и для 0.8

P.S.: Когда нас ждёт следующий релиз?

**Comment by Yiivgeny** [comment]
https://hub.docker.com/r/yiivgeny/pymorphy2/
